language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: PdZyxQlhqaMNe/wWpnM7ez95d+K04XJuyUX0WfGbQ97Gva7QvpaqXWPAFEOH1s345Oy6BJ0Is/AfqpGC28/zBkwKDX7gH5rtSDhf4xyWd3VP749jdPvWYhNFiP2dT06BqBOEOG0aRcHW4yLK2M2QE9+b7YYhIcnw+HErpE0CojPCUCIrALuZkdg0yWaDI86qrTCgyiMtl9PfvbuwbOYHHqS+hSdxjE+9h/SSRTT3fr7Ko3SFfg5FcuEmHuDb2dMBeLnbBll0PSX+WrPxxspMdiWD9/q3AoBd89qeXgXAN0jI9WyRDhqFINbG9T49eS7Pt8RqUMgO7by0vMWo58uRVBQCS3ZQjeVttxerGM0LpiNJk/yJW5vXYB4uJBeOEt0CMu4JOH2hnqBou3sX6DBQVldHG8JfCL8ey6P0rjchV0vpj2qbousPHyPw0Lk8yX2EeMMtPZOAtrp5QYlnbmhtXReJ5BsjCDklEAtWW8paBOzoBOysMeVrTQZdNjUJhpudIkDhkvzRtD+Rjy65B9gJAZQjyJ4fLwowSqvMQGq2pZEEqSjwFMCoPN5Vg6vt6GGbn/+0IOBOPWO3vR4V0s9M42KbYMOl4AQCriFBut/wA0VpaJlwUSHQSZiqBExhLyHoOxkg+yhjK49IkgL86kkoo+hD6wiktgmDWJ50CZ1VyZQ=
  app: pokemon-java-backend
  on:
    repo: bm1216/java-getting-started
