language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: iy8VTXwamjNQzWH5MP2gzaM8XFPP0HudYW2rzalpJqlXe8yqnxCPsrCHPzAQWR+HwlNSXjuZom48dSW0/7AW8NuwjSa7loE5c5TmRKacFIPMM1/dyQr0zPfYOIhh9nrhBmekYnZU7oWfoJ/Uo1BczxHn3B4HaHbBve2SJx/g52W3T39awG3rRy5nQSybojSob0wz+zZrZEj7eUf2ts/b29Zcu+VLoWK1KlfEFVUTFPhJGO4ygdoICS5WXbVJ4pO8naKBwJUxcPVTSaxp+72KQO7I4xosK0d27NoRo49Zl7GpmcDGAkhVkIU60dqcBA8Oh+nnwGKoMpapc34WPqMWRghaMcIS5ynHSPzUjmsdtMPqwqfjLnDQhJhZcRlpqgRhH92PBwtxQNtB5q1KzY+W+tqvhOJE1XhKxzIyZ6z5fiz0ah352xXcFXSaXbKzG0446KryxXsuULf7x8F+bTVFTU//v7TZDYkTvRJnuAPE92OIchDAHaFqJP0v3ZBEbnQLbh9ywcOFWqCxzWFn//iRSwL7rxpV0cVKPdQO6DyLZxnbRja7/2xu5rOL6r4oHKIjlcuVgqoEsxASc6tesMwXdgkchvuCq7d7SdrJBKjzQY4bq8YvVu24drZRNgV4m9FHUuOihaAEHSbo7OnHHpVYnDGNrkyrPBdoyC2njCxS06c=
  app: pokemon-java-backend
  on:
    repo: bm1216/java-getting-started
