language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: DGXI4NOl8c3c77qyUgZBmqjfCANXLv7ohb3jwETsJOvGih+N+Evrsi/xmgUw9jCsY3gcoi/gnf1MVKn/Ic1Tih3k/cRCA+msrFmAG4MH+nSH468nPNv3FOg4ab5faBLZ4AJhNrNJlnaO+2xQtaU+eQdFzZluYLjwDYu5xxjcf4D0OcixE6uDYKS+e3NK3pHIfnGfuN4CydrjHOicdBEnqppAHxqBkjDOtLYImvcUnNfctQI9ERjt5SRye0fbAx+90CSIlIDMIrGoBFjh/ZYckODjHqF218H/9dxLfPn9RsdxGmePaAahoG0irTY5ZxV6lfoUpJLh47+mODID1ON4T5aKBKhSbfp60moEa8eGrwYvP3hLfjnRx6FWFhQxb6LZKYimQoQKOY3PWIjkDmitUgf6NxwgIBLty8Llm14ywpyQo+yKxNFeix2pmDrWAJ616BlMS1NWIbfY4863F8GkLIJE+u7ESwSq4irZcLISKbvSaAYZ2WHgZpDqBDCM24UOMFUjTB8UGmByMoAX8yTzL7txxdc0wmEAX+418ufdb2k21HM+df16yhuUV7EI6dG06C/6MIhjMmvZRilojDeZdo8Nmp3p6Nk3YcOhby06ca0wrNBAosHdgHsdDZau/vwulGhAghgzo8bTAGo+Ap6wbblZk2L92QK+/DcB8cvZSeg=
  app: pokemon-java-backend
